version: '3'

networks:
  default:
    name: auto-eletric-network

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/conf/nginx/empty.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx/my-conf.conf:/etc/nginx/conf.d/my-conf.conf
      - ./docker/conf/nginx/auto-eletric.crt:/etc/nginx/ssl/auto-eletric.pem
      - ./docker/conf/nginx/auto-eletric.key:/etc/nginx/ssl/auto-eletric.key
      - ./docker/conf/hosts:/etc/hosts
      - ./:/var/www/html/jettax-360-api
      - ./logs:/var/log/jettax
      - ./docker/data/history/bash_history:/root/.bash_history
    container_name: auto_eletric_nginx
    links:
      - php
  php:
    build: ./docker
    expose:
      - 9003
    volumes:
      - /etc/default/locale:/etc/default/locale
      - ./:/var/www/html/auto-eletric-api
      - ./docker/conf/php/php-dev.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/hosts:/etc/hosts
      - ./logs:/var/log/auto-eletric-api
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/home:/home/default
    container_name: auto_eletric_php

    links:
      - redis
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - ./docker/data/redis:/data
      container_name: auto_eletric_api_redis
